# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d405dc457963ffd4418eb0e2e7486f5d2ac960aa268b8bd0486f74747a3c460d0baa48fe11a0f7522d4d5d36b57fc00fe73e67b9a4c01b1e395e751f332c20e6

test:
  secret_key_base: f0352165c28e0c3b35ec2a8270063ae1c5b26445b2902a7e35ec144c9f36b7985c3153cc3c26eeac9fe46ebc3ae4d58933184ea90dc22344f9c4b4bdd8c41b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
